// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using AutoStore.Data;

#nullable disable

namespace AutoStore.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20260430174501_UpdateSeedToAutoParts")]
    partial class UpdateSeedToAutoParts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoStore.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("AutoStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Детали двигателя, КПП, сцепление",
                            Name = "Двигатель и трансмиссия"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Колодки, диски, суппорты, шланги",
                            Name = "Тормозная система"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Масляные, воздушные, топливные фильтры и масла",
                            Name = "Фильтры и масла"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Свечи, фары, генераторы, стартеры",
                            Name = "Электрика и освещение"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Амортизаторы, рычаги, рулевые тяги, ШРУС",
                            Name = "Подвеска и рулевое"
                        });
                });

            modelBuilder.Entity("AutoStore.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Москва, Автомоторная ул., 12",
                            Email = "alexey@example.com",
                            FullName = "Алексей Смирнов",
                            Phone = "+7-999-123-45-67",
                            RegisteredAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AutoStore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AutoStore.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AutoStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Фильтр масляный для Volkswagen, Audi, Skoda. Надёжная защита двигателя.",
                            ImageUrl = "https://placehold.co/300x300/1a1a1a/ffffff?text=Oil+Filter",
                            Name = "Масляный фильтр Bosch 0451103079",
                            Price = 650m,
                            Stock = 85
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Передние тормозные колодки для BMW 3/5 серии. Высокоэффективный состав.",
                            ImageUrl = "https://placehold.co/300x300/c62828/ffffff?text=Brake+Pads",
                            Name = "Тормозные колодки Brembo P85020",
                            Price = 3200m,
                            Stock = 42
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Синтетическое моторное масло для бензиновых и дизельных двигателей.",
                            ImageUrl = "https://placehold.co/300x300/ff8f00/ffffff?text=Engine+Oil",
                            Name = "Моторное масло Shell Helix Ultra 5W-40 4л",
                            Price = 4800m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Иридиевые свечи зажигания. Улучшенный запуск, стабильная работа двигателя.",
                            ImageUrl = "https://placehold.co/300x300/212121/ffffff?text=Spark+Plugs",
                            Name = "Свечи зажигания NGK BKR6EK (комплект 4 шт.)",
                            Price = 1890m,
                            Stock = 68
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Газомасляный амортизатор передней подвески для Opel Astra/Zafira.",
                            ImageUrl = "https://placehold.co/300x300/424242/ffffff?text=Shock+Absorber",
                            Name = "Амортизатор передний Sachs 312 456",
                            Price = 5600m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Вентилируемый тормозной диск. Диаметр 300 мм, для Toyota Camry/Lexus ES.",
                            ImageUrl = "https://placehold.co/300x300/b71c1c/ffffff?text=Brake+Disc",
                            Name = "Тормозной диск Ferodo DDF1325",
                            Price = 4100m,
                            Stock = 33
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Фильтр воздушный для Mercedes-Benz C/E-Class. Ресурс 30 000 км.",
                            ImageUrl = "https://placehold.co/300x300/333333/ffffff?text=Air+Filter",
                            Name = "Воздушный фильтр Mann C25114",
                            Price = 980m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Наружный наконечник рулевой тяги для Ford Focus II/III, C-Max.",
                            ImageUrl = "https://placehold.co/300x300/555555/ffffff?text=Tie+Rod",
                            Name = "Рулевая тяга Lemförder 25892 01",
                            Price = 1450m,
                            Stock = 40
                        });
                });

            modelBuilder.Entity("AutoStore.Models.ProductDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("integer");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryOfOrigin = "Германия",
                            Dimensions = "Ø76 × 80 мм",
                            Manufacturer = "Bosch",
                            ProductId = 1,
                            WarrantyMonths = 12,
                            Weight = 0.17999999999999999
                        },
                        new
                        {
                            Id = 2,
                            CountryOfOrigin = "Италия",
                            Dimensions = "155 × 65 × 18 мм",
                            Manufacturer = "Brembo",
                            ProductId = 2,
                            WarrantyMonths = 24,
                            Weight = 0.62
                        },
                        new
                        {
                            Id = 3,
                            CountryOfOrigin = "Нидерланды",
                            Dimensions = "канистра 4 л",
                            Manufacturer = "Shell",
                            ProductId = 3,
                            WarrantyMonths = 0,
                            Weight = 3.6000000000000001
                        },
                        new
                        {
                            Id = 4,
                            CountryOfOrigin = "Япония",
                            Dimensions = "M14 × 1.25, L=26.5 мм",
                            Manufacturer = "NGK",
                            ProductId = 4,
                            WarrantyMonths = 18,
                            Weight = 0.12
                        },
                        new
                        {
                            Id = 5,
                            CountryOfOrigin = "Германия",
                            Dimensions = "L=430 мм, Ø55 мм",
                            Manufacturer = "Sachs",
                            ProductId = 5,
                            WarrantyMonths = 24,
                            Weight = 2.3999999999999999
                        },
                        new
                        {
                            Id = 6,
                            CountryOfOrigin = "Великобритания",
                            Dimensions = "Ø300 × 28 мм",
                            Manufacturer = "Ferodo",
                            ProductId = 6,
                            WarrantyMonths = 24,
                            Weight = 4.7999999999999998
                        });
                });

            modelBuilder.Entity("AutoStore.Models.CartItem", b =>
                {
                    b.HasOne("AutoStore.Models.Customer", "Customer")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoStore.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AutoStore.Models.Order", b =>
                {
                    b.HasOne("AutoStore.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AutoStore.Models.OrderItem", b =>
                {
                    b.HasOne("AutoStore.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoStore.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AutoStore.Models.Product", b =>
                {
                    b.HasOne("AutoStore.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AutoStore.Models.ProductDetails", b =>
                {
                    b.HasOne("AutoStore.Models.Product", "Product")
                        .WithOne("Details")
                        .HasForeignKey("AutoStore.Models.ProductDetails", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AutoStore.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AutoStore.Models.Customer", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AutoStore.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("AutoStore.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Details");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
